# Generated by Django 5.1.3 on 2025-02-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
