# Generated by Django 5.1.3 on 2025-02-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='terms_conditions',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='fb_chat',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='w_chat',
            field=models.URLField(blank=True, null=True),
        ),
    ]
